#ifndef _CONFIG_H_
#define _CONFIG_H_
#define CONFIG_SYS_SDRAM_BASE   0x80000000
#define CONFIG_FPGA_ASPEED
//#define CONFIG_ASPEED_PALLADIUM
//#define CONFIG_ASPEED_DDR4_DUALX8
#define CONFIG_ASPEED_DDR4_1600
//#define CONFIG_ASPEED_DDR4_800
#endif /* end of "#ifndef _CONFIG_H_" */